language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAIKTZEZ6SO4MTN53Q
  secret_access_key:
    secure: j985Li1UVI3zFlMI41vpxjxffMmIIieFq++ijHeUX6edmnq0Aw3YKN1VVAD+z2wtj8irccoAgDszFAOrqhe044gMVTfXUkiNSgweEdu/wwYg3meMvsG7Vy5JNu8KMt9EDr7X2PiAYI6ZXyckAxR8wA862kEmnLUFi8yOA3uZigM3reecwWxd6FqL88kDKQ75Af7on5hWx2xdYgIdbCgdMvNLYluFQ16sJyiSQD8Nh1aM/blA47B8dQyoUkh6zoifU8+dCmv+mpUn8GFTDXkzikELThAVlEidlnILJzSySkBGgq6hdtxIJPFPWAQIo0ZTTNJFayvBRSO4uQHmhbbuu8G/Uo9pvF3uhUZvu3tFgFjwoPXNKmKKg9uI5NUycSukD+a9oYLu9gdCD56xS62OsSGwHlReLXA19xNQsuV7JDOm/FCxikiBEv+aMVlsbrkIqrivdnGGdVneKFozK1Rvg86OXcKOyBE6dQ/hCSWrp58yQuO4SOPnCpBoGrrtXGqYaGAtzhD+ZH7nhl6c4OCqELu+L2651+naaPoIXEsTniJfzZa+Uj8D/llcUMD6meBMgbiqemN9rc3k6Lfvg8VafXrehujrRjUWmqRZfiYnfc6KJiN8lXGemn8DvQ94jQbiz5ErGWnyPv0wFKYjT0Y188PNDhfRm3yndAtpXvYQdto=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: canine_dictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/canine_dictionary
    all_branches: true
