language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIFEO6GSK5
  secret_access_key:
    secure: "tHIPraOtPKZKs3zLrPmriwec3tBVl9NR1wzL1zTbdIWkcIvauhbUTB+ncSoDj4PEItNcdNAkvhc9H4kUTdNNIt6Mz2+FTvh2Q7Tba3gwJu0jjf+bmj6/gRX3XsXZ5MbBVvZh/zWVtxWGXjtwfQwWvYGE6VeDa5IrMey6qcLEM5orM1YnKLKiWkjLWd+MYWRMz///ePJ6VtSoRXd3oq2QLcAkI3qIo9VPpQdMU8yrS4ggm1TWYqMNpIrrUVrpT+tZ8zijgSOafwrm3vygG+g7VAejyua2UgNKpkPDR7jcJYhJUJKPAsurgA1ZdqW2W/S0PAjYm65x9zfE6rGXpn8X3tFimPhv5Z7XZUQdec7CNFj3UyW/wF3lR9iNGtiE/D1mP7fWhfKX8RtMqvBzubZgfNpew4bHf/vGrhLATmcbSg3/4REdWdJfSuYmNXnpPMUvpMKX3hx5qxcMcYAihOnsdBP4t0Q1+FbHoTJM69Fgc7BeR/S1ipXfQ0ar7/EIPIfsNqapnnVfbbICfyrXKog4HwtC1fCr6zDJO8dBPqxbFCG2gAn24s9C6eVJioHvpUN4wZqcEpYfpaC6iqVjglNaQTncLVGfCUjykPpB+4+3Ig0HFdp4Dkao7GFhHQAdFUNu3idnd0KEN5LiSeaMfbqP5W+Rff6+De/LGdlcjL6i37c="
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: canine_dictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/canine_dictionary
    all_branches: true
